[package]
name = "game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "*"
bevy_rapier2d = { version = "*", features = [ "parallel", "debug-render-2d", "enhanced-determinism" ] }
